// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $buscador from "./routes/buscador.tsx";
import * as $crear from "./routes/crear.tsx";
import * as $index from "./routes/index.tsx";
import * as $todos from "./routes/todos.tsx";
import * as $boton from "./islands/boton.tsx";
import * as $buscar from "./islands/buscar.tsx";
import * as $creador from "./islands/creador.tsx";
import * as $personajes from "./islands/personajes.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/buscador.tsx": $buscador,
    "./routes/crear.tsx": $crear,
    "./routes/index.tsx": $index,
    "./routes/todos.tsx": $todos,
  },
  islands: {
    "./islands/boton.tsx": $boton,
    "./islands/buscar.tsx": $buscar,
    "./islands/creador.tsx": $creador,
    "./islands/personajes.tsx": $personajes,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
